# Generated by Django 5.2.3 on 2026-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('author', 'Author'), ('reader', 'Reader')], default='reader', max_length=20),
        ),
    ]
