# Generated by Django 5.2.3 on 2026-08-03 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_publish_post', 'Can publish posts'), ('can_feature_post', 'Can feature posts'), ('can_approve_post', 'Can approve posts')]},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_views_9a8dee_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_author__038a48_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_is_publ_96cac2_idx',
        ),
        migrations.RemoveField(
            model_name='post',
            name='bookmarks',
        ),
        migrations.AddIndex(
            model_name='bookmark',
            index=models.Index(fields=['post'], name='blog_bookma_post_id_410976_idx'),
        ),
    ]
