# Generated by Django 5.2.3 on 2026-08-03 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_options_post_blog_post_views_9a8dee_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_publish_post', 'Can publish posts'), ('can_feature_post', 'Can feature posts'), ('can_approve_post', 'Can approve posts')]},
        ),
    ]
