# Generated by Django 5.2.17 on 2026-08-12 22:23

from django.db import migrations, models


def remap_pending_status(apps, schema_editor):
    """Split the old collapsed "pending" status into in_review/approved,
    and backfill the new status_changed_at/published_at timestamps for
    existing rows so dashboard "Xh ago" labels aren't blank."""
    Post = apps.get_model("blog", "Post")

    Post.objects.filter(status="pending", is_approved=True).update(status="approved")
    Post.objects.filter(status="pending", is_approved=False).update(status="in_review")

    Post.objects.filter(status_changed_at__isnull=True).update(
        status_changed_at=models.F("created_at")
    )
    Post.objects.filter(status="published", published_at__isnull=True).update(
        published_at=models.F("updated_at")
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='editor_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='telegram_announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('needs_changes', 'Needs Changes'), ('approved', 'Approved'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
        migrations.RunPython(remap_pending_status, noop),
    ]
