"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from pathlib import Path
from decouple import config

from csp.constants import NONE, NONCE, SELF, UNSAFE_INLINE

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = config("SECRET_KEY")

DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config(
    "ALLOWED_HOSTS",
    default="127.0.0.1,localhost"
).split(",")

INSTALLED_APPS = [
    'daphne',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',

    'channels',
    'csp',

    'crispy_forms',
    'crispy_bootstrap5',
    'taggit',
    'ckeditor',
    'captcha',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_static',

    'blog',
    'users',
    'chat',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'users.middleware.SessionInactivityTimeoutMiddleware',
    'users.middleware.TwoFactorEnforcementMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND':
        'django.template.backends.django.DjangoTemplates',

        'DIRS': [BASE_DIR / 'templates'],

        'APP_DIRS': True,

        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'blog.context_processors.sidebar_data',
                'blog.context_processors.seo_defaults',
                'chat.context_processors.unread_chat_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
ASGI_APPLICATION = 'config.asgi.application'

# Live chat channel layer.
# Defaults to the in-memory layer, which is fine for a single dev process.
# Set REDIS_URL in production (and run more than one worker) to fan
# messages out across processes via channels_redis.
REDIS_URL = config('REDIS_URL', default='')

if REDIS_URL:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [REDIS_URL],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

DATABASES = {
    'default': {
        'ENGINE':
        'django.db.backends.postgresql',

        'NAME':
        config('DB_NAME'),

        'USER':
        config('DB_USER'),

        'PASSWORD':
        config('DB_PASSWORD'),

        'HOST':
        config('DB_HOST'),

        'PORT':
        config('DB_PORT'),
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]

#Server errors, activities and security logs.

LOG_DIR = BASE_DIR / "logs"
LOG_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    "formatters": {
        "standard": {
            "format": "[%(asctime)s] %(levelname)s %(name)s: %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
    },

    "handlers": {
        "error_file": {
            "level": "ERROR",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "errors.log"),
            "formatter": "standard",
        },

        "security_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "security.log"),
            "formatter": "standard",
        },

        "activity_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "activity.log"),
            "formatter": "standard",
        },

        "csp_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": str(LOG_DIR / "csp_violations.log"),
            "formatter": "standard",
        },

        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },

    "loggers": {
        "django": {
            "handlers": ["error_file", "console"],
            "level": "ERROR",
            "propagate": True,
        },

        "security": {
            "handlers": ["security_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "blog": {
            "handlers": ["activity_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "users": {
            "handlers": ["activity_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "chat": {
            "handlers": ["activity_file", "console"],
            "level": "INFO",
            "propagate": False,
        },

        "csp": {
            "handlers": ["csp_file", "console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = 'home'

# Dev only: prints reset emails to the console instead of sending them.
# Swap for a real SMTP backend before deploying.
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend"
)
DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="noreply@footballhub.local")

# Optional: posts a message to a Telegram channel whenever a post is
# published (see blog.services.telegram). Leave both unset to disable —
# announcements are skipped silently rather than failing the publish action.
TELEGRAM_BOT_TOKEN = config("TELEGRAM_BOT_TOKEN", default="")
TELEGRAM_CHANNEL_ID = config("TELEGRAM_CHANNEL_ID", default="")

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'users.CustomUser'

# Two-factor authentication (django-otp). Privileged roles (see
# users.twofactor.TWO_FACTOR_REQUIRED_ROLES) are forced through TOTP
# enrollment on first login; see users.middleware.TwoFactorEnforcementMiddleware.
OTP_TOTP_ISSUER = "Football Hub"

# Hides the raw TOTP secret key and recovery-code values in the Django admin
# (django_otp's own admin for TOTPDevice/StaticDevice) - superusers can still
# see *whether* a device exists and reset enrollment, just not the secrets.
OTP_ADMIN_HIDE_SENSITIVE_DATA = True

# Login attempt lockout (see users.security)
LOGIN_MAX_FAILED_ATTEMPTS = config("LOGIN_MAX_FAILED_ATTEMPTS", default=5, cast=int)
LOGIN_LOCKOUT_MINUTES = config("LOGIN_LOCKOUT_MINUTES", default=15, cast=int)

# Number of consecutive recent failures (see users.security.failed_streak) after
# which a CAPTCHA is required on the next login attempt for that username.
# Must stay below LOGIN_MAX_FAILED_ATTEMPTS so the CAPTCHA appears before the
# account locks out, not after.
LOGIN_CAPTCHA_AFTER_ATTEMPTS = config("LOGIN_CAPTCHA_AFTER_ATTEMPTS", default=2, cast=int)

# django-simple-captcha
CAPTCHA_CHALLENGE_FUNCT = "captcha.helpers.random_char_challenge"
CAPTCHA_LENGTH = 5
CAPTCHA_TIMEOUT = 5  # minutes before a generated CAPTCHA expires

# Security Settings

X_FRAME_OPTIONS = 'DENY'

SESSION_COOKIE_HTTPONLY = True

# Automatic inactivity timeout (see users.middleware). This is the number
# of seconds of no requests after which an authenticated session is
# treated as expired.
SESSION_INACTIVITY_TIMEOUT = config("SESSION_INACTIVITY_TIMEOUT", default=300, cast=int)

# Backstop at the storage layer: even without the middleware, the session
# store itself will not honour a session older than this many seconds
# since it was last saved. SESSION_SAVE_EVERY_REQUEST makes that a sliding
# window keyed on activity (like the middleware above) rather than a fixed
# time-since-login.
SESSION_COOKIE_AGE = SESSION_INACTIVITY_TIMEOUT
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

CSRF_COOKIE_HTTPONLY = True

SECURE_CONTENT_TYPE_NOSNIFF = True

SECURE_REFERRER_POLICY = 'same-origin'

# Production only (enable after HTTPS is configured) — set these via env vars
# once the site is served over HTTPS. Defaults keep local HTTP dev working:
# All HTTP traffic is redirected to HTTPS.
# Session cookies are only sent over secure HTTPS connections.
# CSRF cookies are only sent over HTTPS.
# HSTS tells browsers to only ever use HTTPS for this host going forward.
SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)

# Content Security Policy (django-csp) — Report-Only for now.
#
# Report-Only mode logs violations to /csp-report/ (see config/views.py)
# instead of blocking them, so real traffic can be reviewed before this
# is promoted to an enforced CONTENT_SECURITY_POLICY. See CSP_NOTES.md
# for what's allowed here, why, and what's needed before enforcing.
# (Named CSP_VIOLATION_REPORT_PATH, not CSP_REPORT_URI — the latter is a
# reserved legacy django-csp<4.0 setting name and trips its migration check.)
CSP_VIOLATION_REPORT_PATH = config("CSP_VIOLATION_REPORT_PATH", default="/csp-report/")

CONTENT_SECURITY_POLICY_REPORT_ONLY = {
    "DIRECTIVES": {
        "default-src": [SELF],

        # HTMX + Bootstrap JS from their CDNs, plus per-request nonces for
        # the few static inline <script> blocks in base.html/profile.html.
        "script-src": [SELF, NONCE, "https://cdn.jsdelivr.net", "https://unpkg.com"],

        # CKEditor 4 (django-ckeditor) applies inline styles to its own
        # editing UI/iframe at runtime via JS, not <style> tags, so there's
        # no <style>/nonce that can cover it — 'unsafe-inline' is required
        # here. See CSP_NOTES.md.
        "style-src": [SELF, UNSAFE_INLINE, "https://cdn.jsdelivr.net"],

        # bootstrap-icons' woff2 files are served from the same jsdelivr CDN
        # as its CSS.
        "font-src": [SELF, "https://cdn.jsdelivr.net"],

        # 'data:' covers the inline QR code image rendered on the 2FA setup
        # page (generated server-side per request, not fetched from
        # anywhere) - see users/views.py:two_factor_setup.
        "img-src": [SELF, "data:"],

        # Same-origin fetch() calls and the chat app's ws:// / wss://
        # WebSocket connections (Django Channels) — 'self' covers both
        # schemes on the current host.
        "connect-src": [SELF],

        # No iframes are embedded by this app, and none of ours should be
        # embedded elsewhere (X_FRAME_OPTIONS already enforces this).
        "frame-src": [NONE],
        "frame-ancestors": [NONE],

        "object-src": [NONE],
        "base-uri": [SELF],
        "form-action": [SELF],

        "report-uri": [CSP_VIOLATION_REPORT_PATH],
    },
}


